version: '3.8'
services:
  db:
    image: postgres
    container_name: postgresDb
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_DB}
    ports:
      - 5432:5432
    networks:
      user_network: 
        aliases:
          - postgresDb

  app:
    container_name: UserService
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./src:/home/app/src
    links:
      - db
    environment:
      DATABASE_URL: ${DATABASE_URL}
    networks:
      user_network: 
        aliases:
          - userService

networks:
  user_network:
    name: MascotasGo_Network
    driver: bridge
    ipam:
      driver: default